function visualize_human_rgb(joints, rgb)
% Visualize tracked human body in rgb image
%
%   Input:
%     joints: human body joints
%     rgb: rgb image;
%

figure; imshow(rgb);
hold on
pj = [joints{enumjoints('Head')}.color' joints{enumjoints('Neck')}.color' ...
      min(joints{enumjoints('Head')}.trackingState, joints{enumjoints('Neck')}.trackingState); ... %Head_Neck
      joints{enumjoints('Neck')}.color' joints{enumjoints('SpineShoulder')}.color' ... 
      min(joints{enumjoints('Neck')}.trackingState, joints{enumjoints('SpineShoulder')}.trackingState); ... %Neck_SpineShoulder
      joints{enumjoints('SpineShoulder')}.color' joints{enumjoints('ShoulderRight')}.color' ... 
      min(joints{enumjoints('SpineShoulder')}.trackingState, joints{enumjoints('ShoulderRight')}.trackingState); ... %SpineShoulder_ShoulderRight
      joints{enumjoints('ShoulderRight')}.color' joints{enumjoints('ElbowRight')}.color' ... 
      min(joints{enumjoints('ShoulderRight')}.trackingState, joints{enumjoints('ElbowRight')}.trackingState); ... %ShoulderRight_ElbowRight
      joints{enumjoints('ElbowRight')}.color' joints{enumjoints('WristRight')}.color' ... 
      min(joints{enumjoints('ElbowRight')}.trackingState, joints{enumjoints('WristRight')}.trackingState); ... %ElbowRight_WristRight
      joints{enumjoints('WristRight')}.color' joints{enumjoints('HandRight')}.color' ... 
      min(joints{enumjoints('WristRight')}.trackingState, joints{enumjoints('HandRight')}.trackingState); ... %WristRight_HandRight
      joints{enumjoints('WristRight')}.color' joints{enumjoints('ThumbRight')}.color' ... 
      min(joints{enumjoints('WristRight')}.trackingState, joints{enumjoints('ThumbRight')}.trackingState); ... %HandRight_ThumbRight
      joints{enumjoints('HandRight')}.color' joints{enumjoints('HandTipRight')}.color' ... 
      min(joints{enumjoints('HandRight')}.trackingState, joints{enumjoints('HandTipRight')}.trackingState); ... %HandRight_HandTipRight
      joints{enumjoints('SpineShoulder')}.color' joints{enumjoints('ShoulderLeft')}.color' ... 
      min(joints{enumjoints('SpineShoulder')}.trackingState, joints{enumjoints('ShoulderLeft')}.trackingState); ... %SpineShoulder_ShoulderLeft
      joints{enumjoints('ShoulderLeft')}.color' joints{enumjoints('ElbowLeft')}.color' ... 
      min(joints{enumjoints('ShoulderLeft')}.trackingState, joints{enumjoints('ElbowLeft')}.trackingState); ... %ShoulderLeft_ElbowLeft
      joints{enumjoints('ElbowLeft')}.color' joints{enumjoints('WristLeft')}.color' ... 
      min(joints{enumjoints('ElbowLeft')}.trackingState, joints{enumjoints('WristLeft')}.trackingState); ... %ElbowLeft_WristLeft
      joints{enumjoints('WristLeft')}.color' joints{enumjoints('HandLeft')}.color' ... 
      min(joints{enumjoints('WristLeft')}.trackingState, joints{enumjoints('HandLeft')}.trackingState); ... %WristLeft_HandLeft
      joints{enumjoints('WristLeft')}.color' joints{enumjoints('ThumbLeft')}.color' ... 
      min(joints{enumjoints('WristLeft')}.trackingState, joints{enumjoints('ThumbLeft')}.trackingState); ... %HandLeft_ThumbLeft
      joints{enumjoints('HandLeft')}.color' joints{enumjoints('HandTipLeft')}.color' ... 
      min(joints{enumjoints('HandLeft')}.trackingState, joints{enumjoints('HandTipLeft')}.trackingState); ... %HandLeft_HandTipLeft
      joints{enumjoints('SpineShoulder')}.color' joints{enumjoints('SpineMid')}.color' ... 
      min(joints{enumjoints('SpineShoulder')}.trackingState, joints{enumjoints('SpineMid')}.trackingState); ... %SpinShoulder_SpineMid
      joints{enumjoints('SpineMid')}.color' joints{enumjoints('SpineBase')}.color' ... 
      min(joints{enumjoints('SpineMid')}.trackingState, joints{enumjoints('SpineBase')}.trackingState); ... %SpineMid_SpineBase
      joints{enumjoints('SpineBase')}.color' joints{enumjoints('HipRight')}.color' ... 
      min(joints{enumjoints('SpineBase')}.trackingState, joints{enumjoints('HipRight')}.trackingState); ... %SpineBase_HipRight
      joints{enumjoints('HipRight')}.color' joints{enumjoints('KneeRight')}.color' ... 
      min(joints{enumjoints('HipRight')}.trackingState, joints{enumjoints('KneeRight')}.trackingState); ... %HipRight_KneeRight
      joints{enumjoints('KneeRight')}.color' joints{enumjoints('AnkleRight')}.color' ... 
      min(joints{enumjoints('KneeRight')}.trackingState, joints{enumjoints('AnkleRight')}.trackingState); ... %KneeRight_AnkleRight
      joints{enumjoints('AnkleRight')}.color' joints{enumjoints('FootRight')}.color' ... 
      min(joints{enumjoints('AnkleRight')}.trackingState, joints{enumjoints('FootRight')}.trackingState); ... %AnkleRight_FootRight
      joints{enumjoints('SpineBase')}.color' joints{enumjoints('HipLeft')}.color' ... 
      min(joints{enumjoints('SpineBase')}.trackingState, joints{enumjoints('HipLeft')}.trackingState); ... %SpineBase_HipLeft
      joints{enumjoints('HipLeft')}.color' joints{enumjoints('KneeLeft')}.color' ... 
      min(joints{enumjoints('HipLeft')}.trackingState, joints{enumjoints('KneeLeft')}.trackingState); ... %HipLeft_KneeLeft
      joints{enumjoints('KneeLeft')}.color' joints{enumjoints('AnkleLeft')}.color' ... 
      min(joints{enumjoints('KneeLeft')}.trackingState, joints{enumjoints('AnkleLeft')}.trackingState); ... %KneeLeft_AnkleLeft
      joints{enumjoints('AnkleLeft')}.color' joints{enumjoints('FootLeft')}.color' ... 
      min(joints{enumjoints('AnkleLeft')}.trackingState, joints{enumjoints('FootLeft')}.trackingState); ... %AnkleLeft_FootLeft
      ]; 
 

for i = 1:size(pj,1)
    if pj(i,5)==2     
        line(pj(i,[1 3]),pj(i,[2 4]),'Color','r','LineWidth',2);
    else
        line(pj(i,[1 3]),pj(i,[2 4]),'Color','g','LineWidth',1);
    end
end 
for i = 1:length(joints)
    if joints{i}.trackingState == 2
        plot(joints{i}.color(1),joints{i}.color(2),'.','Color','g','markers',12);
    else
        plot(joints{i}.color(1),joints{i}.color(2),'.','Color','y','markers',12);
    end
end