function visualize_human_depth(joints, depth)
% Visualize tracked human body in depth image
%
%   Input:
%      joints: human body joints
%     depth: depth image;
%

figure; imshow(depth/max(depth(:)));
hold on
pj = [joints{enumjoints('Head')}.depth' joints{enumjoints('Neck')}.depth' ...
      min(joints{enumjoints('Head')}.trackingState, joints{enumjoints('Neck')}.trackingState); ... %Head_Neck
      joints{enumjoints('Neck')}.depth' joints{enumjoints('SpineShoulder')}.depth' ... 
      min(joints{enumjoints('Neck')}.trackingState, joints{enumjoints('SpineShoulder')}.trackingState); ... %Neck_SpineShoulder
      joints{enumjoints('SpineShoulder')}.depth' joints{enumjoints('ShoulderRight')}.depth' ... 
      min(joints{enumjoints('SpineShoulder')}.trackingState, joints{enumjoints('ShoulderRight')}.trackingState); ... %SpineShoulder_ShoulderRight
      joints{enumjoints('ShoulderRight')}.depth' joints{enumjoints('ElbowRight')}.depth' ... 
      min(joints{enumjoints('ShoulderRight')}.trackingState, joints{enumjoints('ElbowRight')}.trackingState); ... %ShoulderRight_ElbowRight
      joints{enumjoints('ElbowRight')}.depth' joints{enumjoints('WristRight')}.depth' ... 
      min(joints{enumjoints('ElbowRight')}.trackingState, joints{enumjoints('WristRight')}.trackingState); ... %ElbowRight_WristRight
      joints{enumjoints('WristRight')}.depth' joints{enumjoints('HandRight')}.depth' ... 
      min(joints{enumjoints('WristRight')}.trackingState, joints{enumjoints('HandRight')}.trackingState); ... %WristRight_HandRight
      joints{enumjoints('WristRight')}.depth' joints{enumjoints('ThumbRight')}.depth' ... 
      min(joints{enumjoints('WristRight')}.trackingState, joints{enumjoints('ThumbRight')}.trackingState); ... %HandRight_ThumbRight
      joints{enumjoints('HandRight')}.depth' joints{enumjoints('HandTipRight')}.depth' ... 
      min(joints{enumjoints('HandRight')}.trackingState, joints{enumjoints('HandTipRight')}.trackingState); ... %HandRight_HandTipRight
      joints{enumjoints('SpineShoulder')}.depth' joints{enumjoints('ShoulderLeft')}.depth' ... 
      min(joints{enumjoints('SpineShoulder')}.trackingState, joints{enumjoints('ShoulderLeft')}.trackingState); ... %SpineShoulder_ShoulderLeft
      joints{enumjoints('ShoulderLeft')}.depth' joints{enumjoints('ElbowLeft')}.depth' ... 
      min(joints{enumjoints('ShoulderLeft')}.trackingState, joints{enumjoints('ElbowLeft')}.trackingState); ... %ShoulderLeft_ElbowLeft
      joints{enumjoints('ElbowLeft')}.depth' joints{enumjoints('WristLeft')}.depth' ... 
      min(joints{enumjoints('ElbowLeft')}.trackingState, joints{enumjoints('WristLeft')}.trackingState); ... %ElbowLeft_WristLeft
      joints{enumjoints('WristLeft')}.depth' joints{enumjoints('HandLeft')}.depth' ... 
      min(joints{enumjoints('WristLeft')}.trackingState, joints{enumjoints('HandLeft')}.trackingState); ... %WristLeft_HandLeft
      joints{enumjoints('WristLeft')}.depth' joints{enumjoints('ThumbLeft')}.depth' ... 
      min(joints{enumjoints('WristLeft')}.trackingState, joints{enumjoints('ThumbLeft')}.trackingState); ... %HandLeft_ThumbLeft
      joints{enumjoints('HandLeft')}.depth' joints{enumjoints('HandTipLeft')}.depth' ... 
      min(joints{enumjoints('HandLeft')}.trackingState, joints{enumjoints('HandTipLeft')}.trackingState); ... %HandLeft_HandTipLeft
      joints{enumjoints('SpineShoulder')}.depth' joints{enumjoints('SpineMid')}.depth' ... 
      min(joints{enumjoints('SpineShoulder')}.trackingState, joints{enumjoints('SpineMid')}.trackingState); ... %SpinShoulder_SpineMid
      joints{enumjoints('SpineMid')}.depth' joints{enumjoints('SpineBase')}.depth' ... 
      min(joints{enumjoints('SpineMid')}.trackingState, joints{enumjoints('SpineBase')}.trackingState); ... %SpineMid_SpineBase
      joints{enumjoints('SpineBase')}.depth' joints{enumjoints('HipRight')}.depth' ... 
      min(joints{enumjoints('SpineBase')}.trackingState, joints{enumjoints('HipRight')}.trackingState); ... %SpineBase_HipRight
      joints{enumjoints('HipRight')}.depth' joints{enumjoints('KneeRight')}.depth' ... 
      min(joints{enumjoints('HipRight')}.trackingState, joints{enumjoints('KneeRight')}.trackingState); ... %HipRight_KneeRight
      joints{enumjoints('KneeRight')}.depth' joints{enumjoints('AnkleRight')}.depth' ... 
      min(joints{enumjoints('KneeRight')}.trackingState, joints{enumjoints('AnkleRight')}.trackingState); ... %KneeRight_AnkleRight
      joints{enumjoints('AnkleRight')}.depth' joints{enumjoints('FootRight')}.depth' ... 
      min(joints{enumjoints('AnkleRight')}.trackingState, joints{enumjoints('FootRight')}.trackingState); ... %AnkleRight_FootRight
      joints{enumjoints('SpineBase')}.depth' joints{enumjoints('HipLeft')}.depth' ... 
      min(joints{enumjoints('SpineBase')}.trackingState, joints{enumjoints('HipLeft')}.trackingState); ... %SpineBase_HipLeft
      joints{enumjoints('HipLeft')}.depth' joints{enumjoints('KneeLeft')}.depth' ... 
      min(joints{enumjoints('HipLeft')}.trackingState, joints{enumjoints('KneeLeft')}.trackingState); ... %HipLeft_KneeLeft
      joints{enumjoints('KneeLeft')}.depth' joints{enumjoints('AnkleLeft')}.depth' ... 
      min(joints{enumjoints('KneeLeft')}.trackingState, joints{enumjoints('AnkleLeft')}.trackingState); ... %KneeLeft_AnkleLeft
      joints{enumjoints('AnkleLeft')}.depth' joints{enumjoints('FootLeft')}.depth' ... 
      min(joints{enumjoints('AnkleLeft')}.trackingState, joints{enumjoints('FootLeft')}.trackingState); ... %AnkleLeft_FootLeft
      ]; 
 

for i = 1:size(pj,1)
    if pj(i,5)==2     
        line(pj(i,[1 3]),pj(i,[2 4]),'color','r','LineWidth',2);
    else
        line(pj(i,[1 3]),pj(i,[2 4]),'color','g','LineWidth',1);
    end
end 
for i = 1:length(joints)
    if joints{i}.trackingState == 2
        plot(joints{i}.depth(1),joints{i}.depth(2),'.','color','g','markers',12);
    else
        plot(joints{i}.depth(1),joints{i}.depth(2),'.','color','y','markers',12);
    end
end