disp('Compiling matlabCV.cpp');
%% For Mac Platform
mex -I/opt/local/include/opencv -I/usr/local/include/opencv -I/usr/local/include -I/opt/local/include -L/opt/local/lib -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_ml -lopencv_video -lopencv_features2d -lopencv_calib3d -lopencv_objdetect -lopencv_contrib -lopencv_legacy -lopencv_flann matlabCV.cpp -output matlabCV
%% For Windows Platform
%mex matlabCV.cpp -I"C:\SDK\OpenCV2.3\build/include" -I"C:\SDK\OpenCV2.3\build/include/opencv" C:\SDK\OpenCV2.3\build\x64\vc9\lib\opencv_calib3d230.lib C:\SDK\OpenCV2.3\build\x64\vc9\lib\opencv_contrib230.lib C:\SDK\OpenCV2.3\build\x64\vc9\lib\opencv_core230.lib C:\SDK\OpenCV2.3\build\x64\vc9\lib\opencv_features2d230.lib C:\SDK\OpenCV2.3\build\x64\vc9\lib\opencv_flann230.lib C:\SDK\OpenCV2.3\build\x64\vc9\lib\opencv_haartraining_engine.lib C:\SDK\OpenCV2.3\build\x64\vc9\lib\opencv_highgui230.lib C:\SDK\OpenCV2.3\build\x64\vc9\lib\opencv_imgproc230.lib C:\SDK\OpenCV2.3\build\x64\vc9\lib\opencv_legacy230.lib C:\SDK\OpenCV2.3\build\x64\vc9\lib\opencv_ml230.lib C:\SDK\OpenCV2.3\build\x64\vc9\lib\opencv_objdetect230.lib C:\SDK\OpenCV2.3\build\x64\vc9\lib\opencv_video230.lib

disp('Compiling opencvFunc.cpp');
%% For Mac Platform
mex -I/opt/local/include/opencv -I/usr/local/include/opencv -I/usr/local/include -I/opt/local/include -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_ml -lopencv_video -lopencv_features2d -lopencv_calib3d -lopencv_objdetect -lopencv_contrib -lopencv_legacy -lopencv_flann opencvFunc.cpp -output opencvFunc
%% For Windows Platform Matlab 64bit
%mex opencvFunc.cpp -I"C:\SDK\OpenCV2.3\build/include" -I"C:\SDK\OpenCV2.3\build/include/opencv" C:\SDK\OpenCV2.3\build\x64\vc9\lib\opencv_calib3d230.lib C:\SDK\OpenCV2.3\build\x64\vc9\lib\opencv_contrib230.lib C:\SDK\OpenCV2.3\build\x64\vc9\lib\opencv_core230.lib C:\SDK\OpenCV2.3\build\x64\vc9\lib\opencv_features2d230.lib C:\SDK\OpenCV2.3\build\x64\vc9\lib\opencv_flann230.lib C:\SDK\OpenCV2.3\build\x64\vc9\lib\opencv_haartraining_engine.lib C:\SDK\OpenCV2.3\build\x64\vc9\lib\opencv_highgui230.lib C:\SDK\OpenCV2.3\build\x64\vc9\lib\opencv_imgproc230.lib C:\SDK\OpenCV2.3\build\x64\vc9\lib\opencv_legacy230.lib C:\SDK\OpenCV2.3\build\x64\vc9\lib\opencv_ml230.lib C:\SDK\OpenCV2.3\build\x64\vc9\lib\opencv_objdetect230.lib C:\SDK\OpenCV2.3\build\x64\vc9\lib\opencv_video230.lib

%% For Windows Platform Matlab 32bit
%mex opencvFunc.cpp -I"C:\SDK\OpenCV2.3\build/include" -I"C:\SDK\OpenCV2.3\build/include/opencv" C:\SDK\OpenCV2.3\build\x86\vc9\lib\opencv_calib3d230.lib C:\SDK\OpenCV2.3\build\x86\vc9\lib\opencv_contrib230.lib C:\SDK\OpenCV2.3\build\x86\vc9\lib\opencv_core230.lib C:\SDK\OpenCV2.3\build\x86\vc9\lib\opencv_features2d230.lib C:\SDK\OpenCV2.3\build\x86\vc9\lib\opencv_flann230.lib C:\SDK\OpenCV2.3\build\x86\vc9\lib\opencv_haartraining_engine.lib C:\SDK\OpenCV2.3\build\x86\vc9\lib\opencv_highgui230.lib C:\SDK\OpenCV2.3\build\x86\vc9\lib\opencv_imgproc230.lib C:\SDK\OpenCV2.3\build\x86\vc9\lib\opencv_legacy230.lib C:\SDK\OpenCV2.3\build\x86\vc9\lib\opencv_ml230.lib C:\SDK\OpenCV2.3\build\x86\vc9\lib\opencv_objdetect230.lib C:\SDK\OpenCV2.3\build\x86\vc9\lib\opencv_video230.lib